title: "Alloy"
baseURL: "https://www.alloyssg.dev"

build:
  output: _site
  clean: true

content:
  formats: ["md", "html"]
  markdown:
    goldmark:
      unsafe: true
      typographer: true

templates:
  engine: "liquid"

plugins:
  node: true

collections:
  releases:
    sortBy: "date"
    order: "desc"

passthrough:
  - from: "docs/elements"
    to: "lib/alloy-elements"
    exclude:
      - "*.ts"
      - "*.map"

structure:
  content: "docs/content"
  layouts: "docs/layouts"
  static: "docs/static"
  data: "docs/data"
  plugins: "docs/plugins"
