title: "Alloy"
baseURL: "https://www.alloyssg.dev"

build:
  output: _site
  clean: true

content:
  formats: ["md", "html"]
  markdown:
    goldmark:
      unsafe: true
      typographer: true

templates:
  engine: "liquid"

plugins:
  node: true

collections:
  releases:
    sortBy: "date"
    order: "desc"

passthrough:
  - from: "node_modules/@awesome.me/webawesome/dist"
    to: "lib/wa"
    exclude:
      - "*.map"
      - "react/"
      - "ssr/"
      - "skills/"
      - "translations/"
      - "vscode.html-custom-data.json"
      - "web-types.json"
      - "llms.txt"
  - from: "node_modules/lit"
    to: "lib/nm/lit"
    exclude:
      - "*.map"
      - "*.d.ts"
      - "development/"
      - "node/"
  - from: "node_modules/lit-html"
    to: "lib/nm/lit-html"
    exclude:
      - "*.map"
      - "*.d.ts"
      - "development/"
      - "node/"
  - from: "node_modules/lit-element"
    to: "lib/nm/lit-element"
    exclude:
      - "*.map"
      - "*.d.ts"
      - "development/"
      - "node/"
  - from: "node_modules/@lit/reactive-element"
    to: "lib/nm/@lit/reactive-element"
    exclude:
      - "*.map"
      - "*.d.ts"
      - "development/"
      - "node/"
  - from: "node_modules/@shoelace-style/localize/dist"
    to: "lib/nm/@shoelace-style/localize/dist"
    exclude:
      - "*.map"
      - "*.d.ts"
  - from: "node_modules/@lit-labs/ssr-client"
    to: "lib/nm/@lit-labs/ssr-client"
    exclude:
      - "*.map"
      - "*.d.ts"
  - from: "node_modules/nanoid"
    to: "lib/nm/nanoid"
    exclude:
      - "*.d.ts"
      - "bin/"
      - "non-secure/"
      - "async/"
  - from: "node_modules/@floating-ui/dom/dist"
    to: "lib/nm/@floating-ui/dom/dist"
    exclude:
      - "*.d.ts"
      - "*.d.mts"
      - "*.umd.*"
      - "*.min.*"
      - "*.browser.*"
  - from: "node_modules/@floating-ui/core/dist"
    to: "lib/nm/@floating-ui/core/dist"
    exclude:
      - "*.d.ts"
      - "*.d.mts"
      - "*.umd.*"
      - "*.min.*"
  - from: "node_modules/@floating-ui/utils/dist"
    to: "lib/nm/@floating-ui/utils/dist"
    exclude:
      - "*.d.ts"
      - "*.d.mts"
      - "*.umd.*"
      - "*.min.*"
  - from: "node_modules/@floating-ui/utils/dom"
    to: "lib/nm/@floating-ui/utils/dom"
    exclude:
      - "*.d.ts"
      - "*.umd.*"
  - from: "node_modules/composed-offset-position/dist"
    to: "lib/nm/composed-offset-position/dist"
    exclude:
      - "*.d.ts"
      - "*.umd.*"
      - "*.min.*"
      - "*.browser.*"
  - from: "docs/elements"
    to: "lib/alloy-elements"
    exclude:
      - "*.ts"
      - "*.map"

structure:
  content: "docs/content"
  layouts: "docs/layouts"
  static: "docs/static"
  data: "docs/data"
  plugins: "docs/plugins"
