title: "Alloy"
baseURL: "https://www.alloyssg.dev"

build:
  output: _site
  clean: true

content:
  formats: ["md", "html"]
  markdown:
    goldmark:
      unsafe: true
      typographer: true
      templateTags: true

templates:
  engine: "liquid"

permalinks:
  default: "/:slug/"
